env:
  CIRRUS_CLONE_DEPTH: 1
  GITID: ENCRYPTED[77e643d71b80cb0c19742ce4717fe43b42c91f68a7039dd1f1d78fd48966c85c5b3afd23bef21410afa28b82928a8333]
  GITPWD: ENCRYPTED[10c2b5c496ea6fb572d4d89478d90cda8098eb267dd5bfe649137cfe01a2fbb7400a2655151b3a02c12150ac58a71afc]
  chat_id: ENCRYPTED[80e7f2e5a0106ba6d4ad4bae8ff3cb22633e4e65084c5d50a47259ee755fa024335ee38655e58dcb42fc36cc8577e6e2]
  bot_token: ENCRYPTED[af4d4f4b8d4a92ebd8583e1e9a215375e78f37c7664e56a8ee003e8d3a1190e2da231c15dff6b0c2d4fbb16fd86d8d7a]
container:
  image: ubuntu:latest
  cpu: 8
  memory: 8G
  use_in_memory_disk: true
task:
  setup_script:
  - apt-get update && apt-get install -y build-essential bc python curl git zip gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi libssl-dev wget libfl-dev device-tree-compiler bison lz4
  - echo "deb http://archive.ubuntu.com/ubuntu hirsute main" >> /etc/apt/sources.list && apt-get update
  - apt-get --no-install-recommends install libc6 libstdc++6 -y
  build_script:
  - cd ${HOME}
  - git clone https://$GITID:$GITPWD@github.com/ReallySnow-ROM-Testing/android_kernel_google_msm-4.9 -b staging-2 --depth=1 kernel
  - git clone --depth=1 https://github.com/Ratoriku/AnyKernel3.git -b b1c1
  - git clone --depth=1 https://github.com/kdrag0n/proton-clang.git cbl
  - cd kernel
  - ./ci-build
