kind: pipeline
name: ImageBreaker

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
  - name: build
    environment:
      GITID:
        from_secret: GITID
      GITPWD:
        from_secret: GITPWD
    image: ubuntu:20.04
    commands:
      - export HOME=/drone
      - apt-get update && apt-get install -y git && git clone https://$GITID:$GITPWD@github.com/$(cat /drone/src/repo) -b $(cat /drone/src/branch) --depth=1 kernel
      - cd kernel
      - ./drone_build.sh
