version: 2.1
jobs:
  compile:
   docker:
      - image: ubuntu:latest
   steps:
      - run:
          name: Setup Environment
          command: |
           apt-get update && apt-get install -y build-essential bc python curl git zip gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi libssl-dev wget libfl-dev bison cpio
           git clone https://$GITID:$GITPWD@github.com/Ratoriku/msm-4.19 -b main --depth=1 kernel
           git clone --depth=1 https://github.com/Ratoriku/AnyKernel3.git -b sdm660-4.14
           git clone --depth=1 https://github.com/kdrag0n/proton-clang.git cbl
      - run:
          name: Start Building
          command: |
           export HOME=/root/project
           cd kernel
           ./ci-build
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
 